[package]
name = "megalodon"
version = "0.8.7"
edition = "2021"
authors = ["Akira Fukushima <h3.poteto@gmail.com>"]
description = "Mastodon and Pleroma API client library for Rust."
license = "MIT"
repository = "https://github.com/h3poteto/megalodon-rs"
homepage = "https://github.com/h3poteto/megalodon-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"]}
async-trait = "0.1.71"
reqwest = { version = "0.11", features = ["json", "multipart", "stream"] }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7.8", features = ["codec"] }
serde_json = "1.0.100"
serde = { version = "1.0.171", features = ["derive"]}
url = "2.4.0"
oauth2 = { version = "4.4" }
sha1 = { version = "0.10" }
hex = { version = "0.4" }
tokio-tungstenite = { version ="0.19", features = ["native-tls"] }
urlencoding = { version = "2.1" }
log = "0.4"
thiserror = "1"
futures-util = "0.3"
http =  "0.2"

[dev-dependencies]
env_logger = "0.10"
